#!/usr/bin/env bash

set -e -o pipefail

install_packages()
{
	sudo apt-get update
	sudo apt-get install -y --no-install-recommends \
		binfmt-support \
		debootstrap \
		qemu-user-static \
		xz-utils
}

build_sysroot()
{
	local HOST="$1"
	local HOST_NAME=$(sed 's/-unknown//g' <<< "$HOST")
	local arch_name
	local suite

	case $HOST_NAME in
		aarch64-linux-*)
			arch_name="arm64"
			suite="stable"
			;;
		*)
			echo "Target not supported (${HOST})."
			return 1
	esac
	local SYSROOT_NAME="sysroot-${HOST_NAME}"

	sudo rm -rf build
	mkdir build
	pushd build

	sudo rm -rf "${SYSROOT_NAME}"
	sudo debootstrap --arch=${arch_name} --variant=minbase \
		--include=build-essential,symlinks ${suite} "${SYSROOT_NAME}"
	sudo chroot "${SYSROOT_NAME}" symlinks -cr .
	sudo tar -cJvf "../sysroot-${HOST}.tar.xz" "${SYSROOT_NAME}"
	popd
	sudo rm -rf build
}


HOST=$1

if [ -z "${HOST}" ]; then
	echo "[ERROR] Host is missing."
	exit 1
fi

install_packages

build_sysroot "$HOST"
