#!/usr/bin/env bash

set -e -o pipefail

GH_URL_GNU="https://github.com/cross-tools"
GH_URL_MUSL="https://github.com/Matrix3600"
GH_VER_GNU=20260515
GH_VER_MUSL=20260525

LLVM_TARGETS="AArch64;ARM;LoongArch;Mips;PowerPC;RISCV;SystemZ;X86"


function get_build_machine_type()
{
	if [ "$OS" == "Windows_NT" ]; then
		local system="win"
	else
		local system="linux"
		case $(uname -s) in
			Darwin) system="macos" ;;
		esac
	fi
	local arch=""
	case $(uname -m) in
		i?86) arch="x86" ;;
		x86_64|amd64) arch="x64" ;;
		aarch64*|arm64|armv8*) arch="arm64" ;;
	esac
	if [ -n "$arch" ]; then printf '%s\n' "${system}-${arch}"
	else printf '%s\n' "$system"
	fi
}


function install_packages()
{
	local modules="$1"
	local compiler="$2"
	if [ -z "$modules" ]; then
		modules="llvm targets"
	fi
	sudo apt-get update
	local packages="wget xz-utils"

	for module in $modules; do
		case $module in
			llvm)
				packages="${packages} \
					build-essential \
					ca-certificates \
					cmake \
					libz-dev \
					ninja-build \
					python3 \
				"
				case $compiler in
					clang) packages="${packages} clang lld" ;;
				esac
				;;
			*)	# Targets
				;;
		esac
	done

	sudo apt-get install -y --no-install-recommends $packages
}


function build_llvm()
{
	local compiler="$1"
	sudo rm -rf build-llvm
	mkdir build-llvm
	pushd build-llvm

	local options=""
	case $compiler in
		clang)
			options="\
				-DCMAKE_C_COMPILER=clang \
				-DCMAKE_CXX_COMPILER=clang++ \
				-DCMAKE_LINKER_TYPE=LLD \
			" ;;
	esac

	cmake -G Ninja -S ../llvm/llvm $options \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX="$(pwd)/clang-cross" \
		-DLLVM_ENABLE_PROJECTS="clang;lld" \
		-DLLVM_TARGETS_TO_BUILD="${LLVM_TARGETS}" \
		-DCLANG_LINK_CLANG_DYLIB=ON \
		-DLLVM_LINK_LLVM_DYLIB=ON \
		-DLLVM_INSTALL_TOOLCHAIN_ONLY=ON \
		-DENABLE_LINKER_BUILD_ID=ON \
		-DCLANG_DEFAULT_LINKER=lld \
		-DCLANG_DEFAULT_PIE_ON_LINUX=ON \
		-DLLVM_ENABLE_EH=ON \
		-DLLVM_ENABLE_RTTI=ON \
		-DLLVM_ENABLE_ZLIB=ON
	ninja install/strip
	sudo chown -R root:root clang-cross
	echo -e "\nCreating \"clang-cross.tar.xz\" ...\n"
	tar -cJvf "../clang-cross.tar.xz" clang-cross
	popd
	sudo rm -rf build-llvm
}


function build_target()
{
	local TARGET="$1"
	. targets/${TARGET}/config

	sudo rm -rf build
	mkdir build
	pushd build

	tar -xf "../clang-cross.tar.xz"
	sudo chown -R $(id -u):$(id -g) clang-cross
	sudo rm -rf ${TARGET}
	if [ -f "../${TARGET}.tar.xz" ]; then
		tar -xf "../${TARGET}.tar.xz"
	else
		local name="linux-x64_${TARGET}.tar.xz"
		local url=""
		case ${TARGET} in
			*-gnu*)
				url="${GH_URL_GNU}/gnu-cross/releases/download/${GH_VER_GNU}/${TARGET}.tar.xz"
				;;
			*-musl*)
				url="${GH_URL_MUSL}/musl-cross/releases/download/${GH_VER_MUSL}/${name}"
				;;
			*)
				echo "Target not supported (${TARGET})."
				return 1
				;;
		esac
		wget -O - -nv -T 120 --tries=20 "$url" | tar xJ
	fi
	find ${TARGET} -exec chmod +w {} \;
	cp -a ${TARGET}/include clang-cross/
	cp -a ${TARGET}/lib/gcc clang-cross/lib/
	cp -a ${TARGET}/${TARGET} clang-cross/
	rm -rf clang-cross/lib/gcc/${TARGET}/*/{install-tools,plugin}
	rm -rf clang-cross/${TARGET}/{bin,debug-root,lib}
	for n in clang:clang clang++:clang++ cpp:clang-cpp; do
		cat > clang-cross/bin/${TARGET}-${n%%:*} <<-EOF
			#!/bin/sh

			TARGET=${TARGET}
			BINDIR=\$(dirname "\$0")

			exec "\${BINDIR}/${n##*:}" --target=\${TARGET} --sysroot=\${BINDIR}/../\${TARGET}/sysroot ${CLANG_ARGS} "\$@"
		EOF
		chmod +x clang-cross/bin/${TARGET}-${n%%:*}
		cat > clang-cross/bin/${n##*:}.cfg <<-EOF
			--target=${TARGET}
			--sysroot=<CFGDIR>/../${TARGET}/sysroot
			${CLANG_ARGS}
		EOF
	done
	ln -sf ${TARGET}-clang clang-cross/bin/${TARGET}-cc
	ln -sf ${TARGET}-clang++ clang-cross/bin/${TARGET}-c++
	for n in ar:ar c++filt:cxxfilt nm:nm objcopy:objcopy objdump:objdump ranlib:ranlib size:size strings:strings strip:strip; do
		cat > clang-cross/bin/${TARGET}-${n%%:*} <<-EOF
			#!/bin/sh

			BINDIR=\$(dirname "\$0")

			exec "\${BINDIR}/llvm-${n##*:}" "\$@"
		EOF
		chmod +x clang-cross/bin/${TARGET}-${n%%:*}
	done
	find clang-cross -exec chmod a-w {} \;

	# Tarballs
	sudo rm -rf ${TARGET}
	mv clang-cross ${TARGET}
	sudo chown -R root:root ${TARGET}

	local host_name="$(get_build_machine_type)"

	local name="clang-${host_name}_${TARGET}.tar.xz"
	echo -e "\nCreating \"${name}\" ...\n"
	tar -cJvf "../${name}" "${TARGET}"
	local hash="$(sha256sum "../${name}" | awk '{ print $1 }')"
	printf '%s *%s\n' "$hash" "$name" > "../${name}.sha256"
	popd
	sudo rm -rf build
}


TARGET=$1
COMPILER=$2

if [ -z "$TARGET" ]; then
	echo "[ERROR] Target is missing."
	exit 1
fi

if [[ $TARGET != "llvm" && ! -f "targets/${TARGET}/config" ]]; then
	echo "[ERROR] Target not supported (${TARGET})."
	exit 1
fi

install_packages "$TARGET" "$COMPILER"

if [ ! -f "clang-cross.tar.xz" ]; then
	build_llvm "$COMPILER"
fi

if [ "$TARGET" != "llvm" ]; then
	build_target "$TARGET"
fi

echo -e "\nDone.\n"
