#!/usr/bin/env bash

# This script only runs on Linux.

set -e -o pipefail

GH_URL_GNU="https://github.com/cross-tools"
GH_URL_MUSL="https://github.com/Matrix3600"
GH_URL_CLANG="https://github.com/Matrix3600"
GH_VER_GNU=20260515
GH_VER_MUSL=20260528
GH_VER_CLANG=20260528-pre

GH_URL_LLVM_MINGW="https://github.com/mstorsjo"
GH_VER_LLVM_MINGW=20260519
GH_UBNT_VER_LLVM_MINGW=22.04

LLVM_TARGETS="AArch64;ARM;LoongArch;Mips;PowerPC;RISCV;SystemZ;X86"


function get_build_machine_type()
{
	if [ "$OS" == "Windows_NT" ]; then
		local system="win"
	else
		local system="linux"
		case $(uname -s) in
			Linux) ;;
			Darwin) system="macos" ;;
			*) echo "uname -s: \"$(uname -s)\"" >&2 ;;
		esac
	fi
	local arch="unknown"
	case $(uname -m) in
		i?86) arch="x86" ;;
		x86_64|amd64) arch="x64" ;;
		aarch64*|arm64|armv8*) arch="arm64" ;;
		*) echo "uname -m: \"$(uname -m)\"" >&2 ;;
	esac
	printf '%s\n' "${system}-${arch}"
}


#
# Rename conflicting files on case-insensitive file systems.
#

#
# Rename conflicting filenames in include directives.
#
function rename_includes()
{
	if [ -n "$2" ]; then
		local pattern=""
		for name in $2; do
			pattern="${pattern}${pattern:+\\|}${name}"
		done
		find "$1" -type f -print0 | while IFS= read -r -d '' file; do
			sed -i -b -e "s@\(#include\s*<linux/\(${pattern}\)\)\(\.h>\)@\1_1\3@g" "$file"
			if [ $? != 0 ]; then return 1; fi
		done
	fi
}

#
# Rename conflicting files.
#
function rename_files_windows()
{
	local rename_file_list="\
		netfilter/xt_connmark \
		netfilter/xt_dscp \
		netfilter/xt_mark \
		netfilter/xt_rateest \
		netfilter/xt_tcpmss \
		netfilter_ipv4/ipt_ecn \
		netfilter_ipv4/ipt_ttl \
		netfilter_ipv6/ip6t_hl"

	local renamed_files=""
	local root_dir="${1}/sysroot/usr/include/linux"
	find "$root_dir" -exec chmod +w {} \;
	for name in $rename_file_list ;	do
		local ext=".h"
		if [ -f "${root_dir}/${name}${ext}" ]; then
			echo "Renaming \"${root_dir}/${name}${ext}\" to \"${name}_1${ext}\""
			mv "${root_dir}/${name}${ext}" "${root_dir}/${name}_1${ext}"
			if [ $? != 0 ]; then return 1; fi
			renamed_files="${renamed_files} ${name}"
		fi
	done
	rename_includes "$root_dir" "${renamed_files}"
	if [ $? != 0 ]; then return 1; fi
	find "$root_dir" -exec chmod a-w {} \;
}


function is_linux_host()
{
	if [[ $1 =~ mingw ]]; then
		return 1	# false
	else
		return 0	# true
	fi
}


function install_packages()
{
	local modules="$1"
	local host="$2"
	if [ -z "$modules" ]; then
		modules="sysroot llvm targets"
	fi
	local packages="wget xz-utils"

	for module in $modules; do
		case $module in
			llvm)
				packages="${packages} \
					build-essential \
					ca-certificates \
					clang \
					cmake \
					libz-dev \
					lld \
					ninja-build \
					python3 \
				"
				;;
			sysroot)
				packages="${packages} \
					binfmt-support \
					debootstrap \
					qemu-user-static \
				"
				;;
			*)	# Targets
				if ! is_linux_host "$host"; then
					packages="${packages} \
						7zip \
					"
				fi
				;;
		esac
	done

	sudo apt-get update
	sudo apt-get install -y --no-install-recommends $packages
}


function build_sysroot()
{
	local HOST="$1"
	local HOST_NAME=$(sed 's/-unknown//g' <<< "$HOST")
	local arch_name
	local suite

	case $HOST_NAME in
		aarch64-linux-*)
			arch_name="arm64"
			suite="stable"
			;;
		riscv64-linux-*)
			arch_name="riscv64"
			suite="unstable"
			;;
		x86_64-linux-*)
			arch_name="amd64"
			suite="stable"
			;;
		*)
			echo "Host not supported (${HOST})."
			return 1
			;;
	esac
	local SYSROOT_NAME="sysroot-${HOST_NAME}"

	sudo rm -rf build
	mkdir build
	pushd build

	sudo rm -rf "$SYSROOT_NAME"
	sudo debootstrap --arch=${arch_name} --variant=minbase \
		--include=build-essential,symlinks ${suite} "$SYSROOT_NAME"
	sudo chroot "$SYSROOT_NAME" symlinks -cr .
	echo -e "\nCreating \"sysroot-${HOST}.tar.xz\" ...\n"
	sudo tar -cJvf "../sysroot-${HOST}.tar.xz" "$SYSROOT_NAME"
	popd
	sudo rm -rf build
}


function set_cmake_var()
{
	printf 'set(CMAKE_%s "%s")\n' "$1" "$2" >> "toolchain.cmake"
}


function build_llvm()
{
	local HOST="$1"
	local HOST_NAME=$(sed 's/-unknown//g' <<< "$HOST")

	local SYSROOT_NAME=""
	local CC_FLAGS=""

	sudo rm -rf build-llvm
	mkdir build-llvm
	pushd build-llvm

	rm -f toolchain.cmake
	set_cmake_var SYSTEM_PROCESSOR "${HOST%%-*}"

	if is_linux_host "$HOST"; then
		set_cmake_var SYSTEM_NAME Linux
		SYSROOT_NAME="sysroot-${HOST_NAME}"
		set_cmake_var SYSROOT "$(pwd)/${SYSROOT_NAME}"

		sudo rm -rf "${SYSROOT_NAME}"
		sudo tar -xf "../sysroot-${HOST}.tar.xz"
		if [ ! -d "${SYSROOT_NAME}/usr/lib/${HOST_NAME}" ]; then
			echo "[ERROR] Host ${HOST_NAME} not found in sysroot usr/lib."
			return 1
		fi

		set_cmake_var C_COMPILER clang
		set_cmake_var CXX_COMPILER clang++

		# Search latest llvm-strip in PATH
		local llvm_strip=""
		local version=0
		IFS=:
		for p in $PATH; do
			unset IFS
			for name in ${p}/llvm-strip*; do
				if [[ -f $name && $name =~ /llvm-strip(|-([0-9]+))$ ]]; then
					echo "$name"
					local v=${BASH_REMATCH[2]}
					if [ -z "$v" ]; then v=1; fi
					if [[ $v -gt $version ]]; then
						llvm_strip=$name
						version=$v
					fi
				fi
			done
		done
		unset IFS
		if [ -n "$llvm_strip" ]; then
			set_cmake_var STRIP "$llvm_strip"
		fi
	else
		set_cmake_var SYSTEM_NAME Windows
		SYSROOT_NAME="llvm-mingw"
		local build="$(get_build_machine_type)"
		local name
		case $build in
			linux-x64)
				name="llvm-mingw-${GH_VER_LLVM_MINGW}-msvcrt-ubuntu-${GH_UBNT_VER_LLVM_MINGW}-x86_64"
				;;
			linux-arm64)
				name="llvm-mingw-${GH_VER_LLVM_MINGW}-ucrt-ubuntu-${GH_UBNT_VER_LLVM_MINGW}-aarch64"
				;;
			*)
				echo "Build machine not supported (${build})."
				return 1
				;;
		esac
		local url="${GH_URL_LLVM_MINGW}/llvm-mingw/releases/download/${GH_VER_LLVM_MINGW}/${name}.tar.xz"
		wget -O - -nv -T 120 --tries=20 "$url" | tar xJ
		mv "$name" "${SYSROOT_NAME}"
		export PATH="$(pwd)/${SYSROOT_NAME}/bin:$PATH"
		if [ ! -d "${SYSROOT_NAME}/${HOST_NAME}" ]; then
			echo "[ERROR] Host ${HOST_NAME} not supported by llvm-mingw."
			return 1
		fi

		set_cmake_var FIND_ROOT_PATH "$(pwd)/${SYSROOT_NAME}/${HOST_NAME}"
		set_cmake_var GET_RUNTIME_DEPENDENCIES_PLATFORM "windows+pe"
		set_cmake_var C_COMPILER "${HOST_NAME}-clang"
		set_cmake_var CXX_COMPILER "${HOST_NAME}-clang++"
		set_cmake_var STRIP "${HOST_NAME}-strip"

		# Dynamic library for host
		mkdir -p "clang-cross/bin"
		host_lib="${SYSROOT_NAME}/${HOST_NAME}/bin"
		for f in "${host_lib}"/lib*.dll ; do
			if [ -f "$f" ]; then
				echo "Copying \"$f\" to \"clang-cross/bin/\""
				cp "$f" "clang-cross/bin/"
			fi
		done
	fi

	cat - <<-EOF >> toolchain.cmake
		set(CMAKE_C_COMPILER_TARGET $HOST_NAME)
		set(CMAKE_CXX_COMPILER_TARGET $HOST_NAME)
		set(CMAKE_C_FLAGS_INIT "$CC_FLAGS")
		set(CMAKE_CXX_FLAGS_INIT "$CC_FLAGS")
		set(CMAKE_LINKER_TYPE LLD)
		set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
		set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
		set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
		set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
	EOF

	echo -e "\n*** CMAKE toolchain file ***\n"
	cat toolchain.cmake

	cmake -G Ninja -S ../llvm/llvm \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_TOOLCHAIN_FILE="$(pwd)/toolchain.cmake" \
		-DCMAKE_INSTALL_PREFIX="$(pwd)/clang-cross" \
		-DLLVM_ENABLE_PROJECTS="clang;lld" \
		-DLLVM_HOST_TRIPLE=${HOST_NAME} \
		-DLLVM_TARGETS_TO_BUILD="${LLVM_TARGETS}" \
		-DCLANG_LINK_CLANG_DYLIB=ON \
		-DLLVM_LINK_LLVM_DYLIB=ON \
		-DLLVM_INSTALL_TOOLCHAIN_ONLY=ON \
		-DENABLE_LINKER_BUILD_ID=ON \
		-DCLANG_DEFAULT_LINKER=lld \
		-DCLANG_DEFAULT_PIE_ON_LINUX=ON \
		-DLLVM_ENABLE_EH=ON \
		-DLLVM_ENABLE_RTTI=ON \
		-DLLVM_ENABLE_ZLIB=ON
	ninja install/strip

	sudo chown -R root:0 clang-cross
	echo -e "\nCreating \"clang-cross-${HOST}.tar.xz\" ...\n"
	tar -cJvf "../clang-cross-${HOST}.tar.xz" clang-cross
	popd
	sudo rm -rf build-llvm
}


function build_target()
{
	local HOST="$1"
	local TARGET="$2"
	local CLANG_ARGS=""
	. targets/${TARGET}/config

	sudo rm -rf build
	mkdir build
	pushd build

	tar -xf "../clang-cross-${HOST}.tar.xz"
	sudo chown -R $(id -u):$(id -g) clang-cross
	sudo rm -rf ${TARGET}
	if [ -f "../${TARGET}.tar.xz" ]; then
		tar -xf "../${TARGET}.tar.xz"
	else
		local name="linux-x64_${TARGET}.tar.xz"
		local url=""
		case ${TARGET} in
			*-gnu*)
				url="${GH_URL_GNU}/gnu-cross/releases/download/${GH_VER_GNU}/${TARGET}.tar.xz"
				;;
			*-musl*)
				url="${GH_URL_MUSL}/musl-cross/releases/download/x64-${GH_VER_MUSL}/${name}"
				;;
			*)
				echo "Target not supported (${TARGET})."
				return 1
				;;
		esac
		wget -O - -nv -T 120 --tries=20 "$url" | tar xJ
	fi
	find ${TARGET} -exec chmod +w {} \;
	cp -a ${TARGET}/include clang-cross/
	cp -a ${TARGET}/lib/gcc clang-cross/lib/
	cp -a ${TARGET}/${TARGET} clang-cross/
	rm -rf clang-cross/lib/gcc/${TARGET}/*/{install-tools,plugin}
	rm -rf clang-cross/${TARGET}/{bin,debug-root,lib}
	for n in clang:clang clang++:clang++ cpp:clang-cpp; do
		cat > clang-cross/bin/${TARGET}-${n%%:*} <<-EOF
			#!/bin/sh

			TARGET=${TARGET}
			BINDIR=\$(dirname "\$0")

			exec "\${BINDIR}/${n##*:}" --target=\${TARGET} --sysroot=\${BINDIR}/../\${TARGET}/sysroot ${CLANG_ARGS} "\$@"
		EOF
		chmod +x clang-cross/bin/${TARGET}-${n%%:*}
		cat > clang-cross/bin/${n##*:}.cfg <<-EOF
			--target=${TARGET}
			--sysroot=<CFGDIR>/../${TARGET}/sysroot
			${CLANG_ARGS}
		EOF
	done
	ln -sf ${TARGET}-clang clang-cross/bin/${TARGET}-cc
	ln -sf ${TARGET}-clang++ clang-cross/bin/${TARGET}-c++
	for n in ar:ar c++filt:cxxfilt nm:nm objcopy:objcopy objdump:objdump ranlib:ranlib size:size strings:strings strip:strip; do
		cat > clang-cross/bin/${TARGET}-${n%%:*} <<-EOF
			#!/bin/sh

			BINDIR=\$(dirname "\$0")

			exec "\${BINDIR}/llvm-${n##*:}" "\$@"
		EOF
		chmod +x clang-cross/bin/${TARGET}-${n%%:*}
	done

	find clang-cross -exec chmod a-w {} \;

	if ! is_linux_host "$HOST"; then
		rename_files_windows "clang-cross/${TARGET}"
	fi

	local host_name="$(sed 's/-unknown//g' <<< "$HOST")"
	case $host_name in
		aarch64-linux-gnu)
			host_name="linux-arm64" ;;
		aarch64-w64-mingw32)
			host_name="win-arm64" ;;
		riscv64-linux-gnu)
			host_name="linux-riscv64" ;;
		x86_64-linux-gnu)
			host_name="linux-x64" ;;
		x86_64-w64-mingw32)
			host_name="win-x64" ;;
	esac

	# Tarballs
	sudo rm -rf ${TARGET}
	mv clang-cross ${TARGET}
	sudo chown -R root:0 ${TARGET}

	if is_linux_host "$HOST"; then
		local name="clang-${host_name}_${TARGET}.tar.xz"
		echo -e "\nCreating \"${name}\" ...\n"
		tar -cJvf "../${name}" "${TARGET}"
	else
		local name="clang-${host_name}_${TARGET}.7z"
		echo -e "\nCreating \"${name}\" ...\n"
		7z a -mx9 "../${name}" "${TARGET}"
	fi
	local hash="$(sha256sum "../${name}" | awk '{ print $1 }')"
	printf '%s *%s\n' "$hash" "$name" > "../${name}.sha256"
	popd
	sudo rm -rf build
}


HOST=$1
TARGET=$2

if [ -z "$HOST" ]; then
	echo "[ERROR] Host is missing."
	exit 1
fi

if [ -z "$TARGET" ]; then
	echo "[ERROR] Target is missing."
	exit 1
fi

if [[ $TARGET != "sysroot" && $TARGET != "llvm" && \
		! -f "targets/${TARGET}/config" ]]; then
	echo "[ERROR] Target not supported (${TARGET})."
	exit 1
fi

install_packages "$TARGET" "$HOST"

if is_linux_host "$HOST" && [[ ! -f "sysroot-${HOST}.tar.xz" && \
		! -f "clang-cross-${HOST}.tar.xz" ]]; then
	build_sysroot "$HOST"
fi

if [[ $TARGET != "sysroot" && ! -f "clang-cross-${HOST}.tar.xz" ]]; then
	url="${GH_URL_CLANG}/clang-cross/releases/download/${GH_VER_CLANG}/clang-cross-${HOST}.tar.xz"
	if ! wget -nv -nc -T 120 --tries=20 "$url" 2>/dev/null; then
		build_llvm "$HOST"
	fi
fi

if [[ $TARGET != "sysroot" && $TARGET != "llvm" ]]; then
	build_target "$HOST" "$TARGET"
fi

echo -e "\nDone.\n"
