#!/usr/bin/env bash

# This script requires a case-sensitive file system.
# Otherwise some header files will be lost in the sysroot include folder.

set -e -o pipefail

. "$(dirname "$0")/tools/common.sh"


function install_packages()
{
	local system
	system="$(get_build_machine_type)"
	system=${system%%-*}

	local packages="
		ca-certificates \
		cmake \
		python3 \
		wget \
	"
	case $system in
		linux)
			packages="${packages} \
				build-essential \
				clang \
				libz-dev \
				lld \
				ninja-build \
				patch \
				xz-utils \
			"
		;;
		macos)
			packages="${packages} \
				bash \
				gnu-sed \
				libelf \
				lld \
				llvm \
				ninja \
				xz \
			"
		;;
	esac
	case $system in
		linux)
			sudo apt-get update
			sudo apt-get install -y --no-install-recommends $packages
		;;
		macos)
			brew update
			brew uninstall python ruby
			brew install --quiet $packages
		;;
	esac
}


function build_llvm()
{
	local DEFAULT_TARGET="$1"

	local llvm_version
	llvm_version="$(get_llvm_version)"

	sudo rm -rf build-llvm
	mkdir build-llvm
	pushd build-llvm

	show_progress_message "Configuring LLVM ${llvm_version}"

	local LLVM_TARGETS="AArch64;ARM;LoongArch;Mips;PowerPC;RISCV;SystemZ;X86"
	local options=""
	if [ -n "$DEFAULT_TARGET" ]; then
		options="${options} -DLLVM_DEFAULT_TARGET_TRIPLE=${DEFAULT_TARGET}"
	fi

	cmake -G Ninja -S ../llvm/llvm $options \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_C_COMPILER=clang \
		-DCMAKE_CXX_COMPILER=clang++ \
		-DCMAKE_INSTALL_PREFIX="$(pwd)/clang-cross" \
		-DLLVM_ENABLE_PROJECTS="clang;lld" \
		-DLLVM_TARGETS_TO_BUILD="${LLVM_TARGETS}" \
		-DLLVM_USE_LINKER=lld \
		-DCLANG_LINK_CLANG_DYLIB=ON \
		-DLLVM_LINK_LLVM_DYLIB=ON \
		-DLLVM_INSTALL_TOOLCHAIN_ONLY=ON \
		-DENABLE_LINKER_BUILD_ID=ON \
		-DCLANG_DEFAULT_LINKER=lld \
		-DCLANG_DEFAULT_PIE_ON_LINUX=ON \
		-DLLVM_ENABLE_LIBXML2=OFF \
		-DLLVM_ENABLE_EH=ON \
		-DLLVM_ENABLE_RTTI=ON \
		-DLLVM_ENABLE_ZLIB=ON

	show_progress_message "Building LLVM ${llvm_version}"

	ninja install/strip

	sudo chown -R root:0 clang-cross

	local host_type
	host_type="$(get_build_machine_type)"
	if [ -n "$DEFAULT_TARGET" ]; then
		local name="llvm-clang-${host_type}-${llvm_version}_${DEFAULT_TARGET}.tar.xz"
	else
		local name="llvm-clang-${host_type}-${llvm_version}.tar.xz"
	fi

	show_progress_message "Creating \"${name}\""

	tar -cJvf "../${name}" clang-cross
	popd
	sudo rm -rf build-llvm

	echo -e "\nThe compiler alone, without the C library, is in"
	echo -e "${name} .\n"
}


function build_target()
{
	local TARGET="$1"
	local DEFAULT_TARGET="$2"
	local SCRIPTS="$(pwd)/scripts/tools"

	local llvm_version
	llvm_version="$(get_llvm_version)"

	local src_dir="$CROSS_CLANG_SOURCE_DIR"
	if [ -z "$src_dir" ]; then
		src_dir="source-tarballs"
	fi
	set +e
	local source_dir="$(mkdir -p -- "$src_dir" &>/dev/null && \
		cd -- "$src_dir" &>/dev/null && pwd)"
	set -e
	if [ -z "$source_dir" ]; then
		echo "[ERROR] Source directory invalid (${src_dir})." >&2
		return 1
	fi
	export CROSS_CLANG_TARGET_SOURCE_DIR="$source_dir"

	sudo rm -rf build
	mkdir build
	pushd build

	local host_type
	host_type="$(get_build_machine_type)"
	if [ -n "$DEFAULT_TARGET" ]; then
		local name="../llvm-clang-${host_type}-${llvm_version}_${DEFAULT_TARGET}.tar.xz"
	else
		local name="../llvm-clang-${host_type}-${llvm_version}.tar.xz"
	fi
	tar -xf "$name"

	"${SCRIPTS}/build_target.sh" "$TARGET" "$(pwd)/clang-cross/bin" "$DEFAULT_TARGET"

	# Tarballs
	sudo rm -rf ${TARGET}
	mv clang-cross ${TARGET}
	sudo chown -R root:0 ${TARGET}

	local name="clang-${host_type}_${TARGET}.tar.xz"

	show_progress_message "Creating \"${name}\""

	tar -cJvf "../${name}" "${TARGET}"
	local hash
	hash="$(sha256sum "../${name}" | awk '{ print $1 }')"
	printf '%s *%s\n' "$hash" "$name" > "../${name}.sha256"
	popd
	sudo rm -rf build

	echo -e "\nThe complete toolchain is in"
	echo -e "${name} .\n"
}


TARGET=$1
DEFAULT_TARGET=$2

if [ -z "$TARGET" ]; then
	echo "[ERROR] Target is missing." >&2
	exit 1
fi

if [[ $TARGET != "llvm" && ! -f "targets/${TARGET}/config" ]]; then
	echo "[ERROR] Target not supported (${TARGET})." >&2
	exit 1
fi

install_packages

llvm_version="$(get_llvm_version)"
host_type="$(get_build_machine_type)"
llvm_prefix="llvm-clang-${host_type}-${llvm_version}"

if [ -n "$DEFAULT_TARGET" ]; then
	llvm_tarname="${llvm_prefix}_${DEFAULT_TARGET}.tar.xz"
else
	llvm_tarname="${llvm_prefix}.tar.xz"
	if [ ! -f "$llvm_tarname" ]; then
		for name in ${llvm_prefix}_*.tar.xz; do
			if [[ -f $name && $name =~ ^${llvm_prefix}_(.+)\.tar\.xz$ ]]; then
				DEFAULT_TARGET=${BASH_REMATCH[1]}
				llvm_tarname="${llvm_prefix}_${DEFAULT_TARGET}.tar.xz"
				break
			fi
		done
	fi
fi

if [[ $CROSS_CLANG_RESUME == "true" && ! -f "$llvm_tarname" ]]; then
	url="${CROSS_CLANG_URL}/clang-cross/releases/download/${CROSS_CLANG_LATEST}/${llvm_tarname}"
	wget -nv -nc -T 120 --tries=20 "$url" 2>/dev/null || true
fi

if [[ -z $DEFAULT_TARGET && ! -f "$llvm_tarname" && \
		$TARGET != "sysroot" && $TARGET != "llvm" ]]; then
	DEFAULT_TARGET=$TARGET
	llvm_tarname="${llvm_prefix}_${DEFAULT_TARGET}.tar.xz"
fi

if [ ! -f "$llvm_tarname" ]; then
	build_llvm "$DEFAULT_TARGET"
fi

if [ "$TARGET" != "llvm" ]; then
	build_target "$TARGET" "$DEFAULT_TARGET"
fi

echo -e "\nDone.\n"
