#!/usr/bin/env bash

set -e -o pipefail

install_packages()
{
	sudo apt-get update
	sudo apt-get install -y --no-install-recommends \
		binfmt-support \
		debootstrap \
		qemu-user-static \
		xz-utils
}

build_sysroot()
{
	local HOST="$1"
	local host_name=$(sed 's/-unknown//g' <<< "$HOST")
	local arch_name

	case host_name in
		aarch64-linux-*)
			arch_name="arm64" ;;
		*)
			echo "Target not supported (${HOST})."
			return 1
	esac

	sudo rm -rf build
	mkdir build
	pushd build

	sysroot_name="sysroot-deb-${arch_name}-stable"

	sudo rm -rf "${sysroot_name}"
	sudo debootstrap --arch=${arch_name} --variant=minbase --include=build-essential,symlinks stable ${sysroot_name}
	sudo chroot ${sysroot_name} symlinks -cr .
	sudo tar -cJvf "../sysroot-${HOST}.tar.xz" ${sysroot_name}
	popd
	sudo rm -rf build
}


HOST=$1

if [ -z "${HOST}" ]; then
	echo "[ERROR] Host is missing."
	exit 1
fi

install_packages

build_sysroot "$HOST"
