#!/usr/bin/env bash

set -e -o pipefail

GH_URL_GNU="https://github.com/cross-tools"
GH_URL_MUSL="https://github.com/Matrix3600"
GH_VER_GNU=20260515
GH_VER_MUSL=20260515

LLVM_TARGETS="AArch64;ARM;LoongArch;Mips;PowerPC;RISCV;SystemZ;X86"


install_packages()
{
	local modules="$1"
	if [ -z "$modules" ]; then
		modules="llvm targets"
	fi
	sudo apt-get update
	local packages="wget xz-utils"

	for module in $modules; do
		case $module in
			llvm)
				packages="${packages} \
					build-essential \
					ca-certificates \
					clang \
					cmake \
					libz-dev \
					lld \
					ninja-build \
					python3 \
				"
				;;
			*)	# Targets
				;;
		esac
	done

	sudo apt-get install -y --no-install-recommends $packages
}


build_llvm()
{
	sudo rm -rf build-llvm
	mkdir build-llvm
	pushd build-llvm

	cmake -G Ninja -S ../llvm/llvm \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX="$(pwd)/clang-cross" \
		-DLLVM_ENABLE_PROJECTS="clang;lld" \
		-DLLVM_TARGETS_TO_BUILD="${LLVM_TARGETS}" \
		-DCMAKE_C_COMPILER=clang \
		-DCMAKE_CXX_COMPILER=clang++ \
		-DCMAKE_LINKER_TYPE=LLD \
		-DCLANG_LINK_CLANG_DYLIB=ON \
		-DLLVM_LINK_LLVM_DYLIB=ON \
		-DLLVM_INSTALL_TOOLCHAIN_ONLY=ON \
		-DENABLE_LINKER_BUILD_ID=ON \
		-DCLANG_DEFAULT_LINKER=lld \
		-DCLANG_DEFAULT_PIE_ON_LINUX=ON \
		-DLLVM_ENABLE_EH=ON \
		-DLLVM_ENABLE_RTTI=ON \
		-DLLVM_ENABLE_ZLIB=ON
	ninja install/strip
	sudo chown -R root:root clang-cross
	echo -e "\nCreating \"clang-cross.tar.xz\" ...\n"
	tar -cJvf ../clang-cross.tar.xz clang-cross
	popd
	sudo rm -rf build-llvm
}


build_target()
{
	local TARGET="$1"
	. targets/${TARGET}/config

	sudo rm -rf build
	mkdir build
	pushd build

	tar -xf ../clang-cross.tar.xz
	sudo chown -R $(id -u):$(id -g) clang-cross
	sudo rm -rf ${TARGET}
	if [ -f "../${TARGET}.tar.xz" ]; then
		tar -xf "../${TARGET}.tar.xz"
	else
		local url=""
		case ${TARGET} in
			*-gnu*)
				url="${GH_URL_GNU}/gnu-cross/releases/download/${GH_VER_GNU}/${TARGET}.tar.xz"
				;;
			*-musl*)
				url="${GH_URL_MUSL}/musl-cross/releases/download/${GH_VER_MUSL}/${TARGET}.tar.xz"
				;;
			*)
				echo "Target not supported (${TARGET})."
				return 1
				;;
		esac
		wget -O - -T 120 --tries=20 "$url" | tar xJ
	fi
	find ${TARGET} -exec chmod +w {} \;
	cp -a ${TARGET}/include clang-cross/
	cp -a ${TARGET}/lib/gcc clang-cross/lib/
	cp -a ${TARGET}/${TARGET} clang-cross/
	rm -rf clang-cross/lib/gcc/${TARGET}/*/{install-tools,plugin}
	rm -rf clang-cross/${TARGET}/{bin,debug-root,lib}
	for n in clang:clang clang++:clang++ cpp:clang-cpp; do
		cat > clang-cross/bin/${TARGET}-${n%%:*} <<-EOF
			#!/bin/sh

			TARGET=${TARGET}
			BINDIR=\$(dirname "\$0")

			exec "\${BINDIR}/${n##*:}" --target=\${TARGET} --sysroot=\${BINDIR}/../\${TARGET}/sysroot ${CLANG_ARGS} "\$@"
		EOF
		chmod +x clang-cross/bin/${TARGET}-${n%%:*}
		cat > clang-cross/bin/${n##*:}.cfg <<-EOF
			--target=${TARGET}
			--sysroot=<CFGDIR>/../${TARGET}/sysroot
			${CLANG_ARGS}
		EOF
	done
	ln -sf ${TARGET}-clang clang-cross/bin/${TARGET}-cc
	ln -sf ${TARGET}-clang++ clang-cross/bin/${TARGET}-c++
	for n in ar:ar c++filt:cxxfilt nm:nm objcopy:objcopy objdump:objdump ranlib:ranlib size:size strings:strings strip:strip; do
		cat > clang-cross/bin/${TARGET}-${n%%:*} <<-EOF
			#!/bin/sh

			BINDIR=\$(dirname "\$0")

			exec "\${BINDIR}/llvm-${n##*:}" "\$@"
		EOF
		chmod +x clang-cross/bin/${TARGET}-${n%%:*}
	done
	find clang-cross -exec chmod a-w {} \;
	sudo rm -rf ${TARGET}
	mv clang-cross ${TARGET}
	sudo chown -R root:root ${TARGET}
	name="clang-${TARGET}"
	echo -e "\nCreating \"${name}.tar.xz\" ...\n"
	tar -cJvf ../${name}.tar.xz ${TARGET}
	sha256sum ../${name}.tar.xz | awk '{ print $1 }' > ../${name}.tar.xz.sha256
	popd
	sudo rm -rf build
}


TARGET=$1

if [ -z "$TARGET" ]; then
	echo "[ERROR] Target is missing."
	exit 1
fi

if [[ $TARGET != "llvm" && ! -f "targets/${TARGET}/config" ]]; then
	echo "[ERROR] Target not supported (${TARGET})."
	exit 1
fi

install_packages "$TARGET"

if [ ! -f "clang-cross.tar.xz" ]; then
	build_llvm
fi

if [ "$TARGET" != "llvm" ]; then
	build_target "$TARGET"
fi

echo -e "\nDone.\n"
